"""init all models

Revision ID: 9f67d4c6ab11
Revises: 
Create Date: 2026-03-05 06:41:00.074393+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f67d4c6ab11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='节点唯一编码，如 STUDY-001, ANALYSIS-DM-001'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='节点显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='节点详细描述'),
    sa.Column('node_type', sa.Enum('CDISC', 'GLOBAL', 'TA', 'COMPOUND', 'INDICATION', 'STUDY', 'ANALYSIS', name='node_type_enum'), nullable=False, comment='节点类型：CDISC/Global/TA/Compound/Indication/Study/Analysis'),
    sa.Column('lifecycle_status', sa.Enum('PLANNING', 'ONGOING', 'TERMINATED', 'COMPLETED', name='lifecycle_status_enum'), nullable=False, comment='生命周期状态，影响分析只扫描 Ongoing 节点'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父节点 ID，根节点为 NULL'),
    sa.Column('path', sa.String(length=1000), nullable=True, comment="物化路径，如 '/1/5/12/'，用于快速查询祖先和后代"),
    sa.Column('depth', sa.Integer(), nullable=False, comment='层级深度，根节点为 0'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级节点排序序号'),
    sa.Column('version_pinning', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='版本锁定信息，记录从上级继承的元数据版本及豁免状态'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性，存储节点特定的配置信息'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='作用域节点表 - 树状层级结构核心表'
    )
    op.create_index('ix_scope_nodes_active', 'scope_nodes', ['is_deleted', 'lifecycle_status'], unique=False)
    op.create_index(op.f('ix_scope_nodes_code'), 'scope_nodes', ['code'], unique=True)
    op.create_index(op.f('ix_scope_nodes_is_deleted'), 'scope_nodes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scope_nodes_lifecycle_status'), 'scope_nodes', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_scope_nodes_node_type'), 'scope_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_scope_nodes_parent_id'), 'scope_nodes', ['parent_id'], unique=False)
    op.create_index('ix_scope_nodes_parent_type', 'scope_nodes', ['parent_id', 'node_type'], unique=False)
    op.create_index('ix_scope_nodes_type_status', 'scope_nodes', ['node_type', 'lifecycle_status'], unique=False)
    op.create_table('analysis_workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='所属作用域节点 ID（通常为 Analysis 层级）'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='工作区编码，如 WS-BLIND-001'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='工作区显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工作区详细描述'),
    sa.Column('workspace_type', sa.Enum('BLINDED', 'UNBLINDED', name='workspace_type_enum'), nullable=False, comment='工作区类型：Blinded（盲态）/ Unblinded（非盲态）'),
    sa.Column('visibility_context', sa.Enum('ALL', 'BLINDED_ONLY', 'UNBLINDED_ONLY', name='visibility_context_enum'), nullable=False, comment='可见性上下文，用于权限过滤'),
    sa.Column('server_host', sa.String(length=255), nullable=False, comment='服务器主机名或 IP'),
    sa.Column('server_path', sa.String(length=500), nullable=False, comment='服务器上的物理路径，如 /data/studies/STUDY001/blinded/'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='工作区是否激活'),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='连接配置，如 SSH 密钥、SAS 路径等'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='分析工作区表 - 盲态隔离核心表'
    )
    op.create_index(op.f('ix_analysis_workspaces_is_deleted'), 'analysis_workspaces', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_analysis_workspaces_scope_node_id'), 'analysis_workspaces', ['scope_node_id'], unique=False)
    op.create_index(op.f('ix_analysis_workspaces_workspace_type'), 'analysis_workspaces', ['workspace_type'], unique=False)
    op.create_index('ix_workspaces_active', 'analysis_workspaces', ['is_deleted', 'is_active'], unique=False)
    op.create_index('ix_workspaces_type_visibility', 'analysis_workspaces', ['workspace_type', 'visibility_context'], unique=False)
    op.create_index('uix_workspaces_node_code', 'analysis_workspaces', ['scope_node_id', 'code'], unique=True)
    op.create_table('ars_displays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='所属作用域节点 ID（通常为 Analysis 层级）'),
    sa.Column('display_id', sa.String(length=50), nullable=False, comment="显示 ID，如 'Table 14.1.1', 'Figure 1.1'"),
    sa.Column('display_type', sa.String(length=20), nullable=False, comment='显示类型：Table / Figure / Listing'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=500), nullable=True, comment='副标题'),
    sa.Column('footnote', sa.Text(), nullable=True, comment='脚注'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('display_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='显示配置，如页面大小、边距等'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='ARS 显示表 - TFL 输出定义'
    )
    op.create_index(op.f('ix_ars_displays_display_id'), 'ars_displays', ['display_id'], unique=False)
    op.create_index(op.f('ix_ars_displays_is_deleted'), 'ars_displays', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ars_displays_scope_node_id'), 'ars_displays', ['scope_node_id'], unique=False)
    op.create_index('uix_ars_displays_scope_id', 'ars_displays', ['scope_node_id', 'display_id'], unique=True)
    op.create_table('ars_template_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='所属作用域节点 ID'),
    sa.Column('block_name', sa.String(length=100), nullable=False, comment='模块名称'),
    sa.Column('block_type', sa.String(length=20), nullable=False, comment='模块类型：Header / Row / Cell / Section'),
    sa.Column('description', sa.Text(), nullable=True, comment='模块描述'),
    sa.Column('layout_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='布局 Schema，包含缩进、统计量配置、样式等'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='ARS 模板块表 - TFL 模板组件'
    )
    op.create_index(op.f('ix_ars_template_blocks_block_name'), 'ars_template_blocks', ['block_name'], unique=False)
    op.create_index(op.f('ix_ars_template_blocks_is_deleted'), 'ars_template_blocks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ars_template_blocks_scope_node_id'), 'ars_template_blocks', ['scope_node_id'], unique=False)
    op.create_index('uix_ars_blocks_scope_name', 'ars_template_blocks', ['scope_node_id', 'block_name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'RESTORE', name='audit_action_enum'), nullable=False, comment='操作类型：CREATE/UPDATE/DELETE/RESTORE'),
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='目标表名'),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='目标记录 ID'),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更前的值（CREATE 操作为 NULL）'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更后的值（DELETE 操作为 NULL）'),
    sa.Column('diff_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='差异快照，仅包含变更的字段'),
    sa.Column('operation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='操作上下文，如请求 ID、客户端 IP 等'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='操作者用户 ID'),
    sa.Column('user_name', sa.String(length=255), nullable=True, comment='操作者用户名（冗余，方便查询）'),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='操作时间戳'),
    sa.Column('reason', sa.Text(), nullable=True, comment='操作原因（必填项，由业务层强制校验）'),
    sa.Column('scope_node_id', sa.Integer(), nullable=True, comment='关联的作用域节点 ID'),
    sa.Column('pull_request_id', sa.Integer(), nullable=True, comment='关联的 Pull Request ID'),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='审计日志表 - 21 CFR Part 11 合规核心表'
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_time', 'audit_logs', ['action', 'action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_timestamp'), 'audit_logs', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_pull_request_id'), 'audit_logs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_scope_node_id'), 'audit_logs', ['scope_node_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index('ix_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_time', 'audit_logs', ['user_id', 'action_timestamp'], unique=False)
    op.create_table('metadata_pull_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pr_number', sa.String(length=20), nullable=False, comment="PR 编号，如 'PR-2024-0001'"),
    sa.Column('title', sa.String(length=200), nullable=False, comment='PR 标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='PR 描述'),
    sa.Column('requester_id', sa.String(length=100), nullable=False, comment='请求者用户 ID'),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True, comment='审核者用户 ID'),
    sa.Column('source_scope_id', sa.Integer(), nullable=False, comment='源作用域 ID（如 Study）'),
    sa.Column('target_scope_id', sa.Integer(), nullable=False, comment='目标作用域 ID（如 Global/TA）'),
    sa.Column('item_type', sa.Enum('TFL', 'MAPPING', 'SPEC', name='pr_item_type_enum'), nullable=False, comment='变更项目类型：TFL/Mapping/Spec'),
    sa.Column('item_id', sa.Integer(), nullable=False, comment='变更项目 ID'),
    sa.Column('diff_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='变更快照，包含 before/after 的完整数据'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MERGED', name='pr_status_enum'), nullable=False, comment='PR 状态：Pending/Approved/Rejected/Merged'),
    sa.Column('impact_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='影响分析结果，包含受影响的下游 Study/Analysis 数量'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='提交时间'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间'),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True, comment='合并时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_scope_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_scope_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='元数据拉取请求表 - PR 审批流核心表'
    )
    op.create_index(op.f('ix_metadata_pull_requests_is_deleted'), 'metadata_pull_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_item_id'), 'metadata_pull_requests', ['item_id'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_item_type'), 'metadata_pull_requests', ['item_type'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_pr_number'), 'metadata_pull_requests', ['pr_number'], unique=True)
    op.create_index(op.f('ix_metadata_pull_requests_requester_id'), 'metadata_pull_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_reviewer_id'), 'metadata_pull_requests', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_source_scope_id'), 'metadata_pull_requests', ['source_scope_id'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_status'), 'metadata_pull_requests', ['status'], unique=False)
    op.create_index(op.f('ix_metadata_pull_requests_target_scope_id'), 'metadata_pull_requests', ['target_scope_id'], unique=False)
    op.create_index('ix_prs_requester_status', 'metadata_pull_requests', ['requester_id', 'status'], unique=False)
    op.create_index('ix_prs_reviewer_status', 'metadata_pull_requests', ['reviewer_id', 'status'], unique=False)
    op.create_index('ix_prs_source_type_status', 'metadata_pull_requests', ['source_scope_id', 'item_type', 'status'], unique=False)
    op.create_table('source_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='所属作用域节点 ID'),
    sa.Column('collection_name', sa.String(length=100), nullable=False, comment="集合名称，如 'Vital Signs', 'Adverse Events'"),
    sa.Column('collection_oid', sa.String(length=100), nullable=True, comment='集合 OID（来自 EDC 系统的唯一标识）'),
    sa.Column('description', sa.Text(), nullable=True, comment='集合描述'),
    sa.Column('source_type', sa.Enum('EDC', 'EDT', 'SAAS', 'MANUAL', name='source_type_enum'), nullable=False, comment='源数据类型：EDC/eDT/SaaS/Manual'),
    sa.Column('source_system', sa.String(length=100), nullable=True, comment="源系统名称，如 'Medidata Rave', 'Oracle InForm'"),
    sa.Column('source_version', sa.String(length=50), nullable=True, comment='源系统版本'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('raw_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='原始属性，存储从源系统导入的杂项属性'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='源数据集合表 - EDC 表单/eDT 数据集定义'
    )
    op.create_index(op.f('ix_source_collections_collection_name'), 'source_collections', ['collection_name'], unique=False)
    op.create_index(op.f('ix_source_collections_is_deleted'), 'source_collections', ['is_deleted'], unique=False)
    op.create_index('ix_source_collections_oid', 'source_collections', ['collection_oid'], unique=False)
    op.create_index(op.f('ix_source_collections_scope_node_id'), 'source_collections', ['scope_node_id'], unique=False)
    op.create_index('uix_source_collections_scope_name', 'source_collections', ['scope_node_id', 'collection_name'], unique=True)
    op.create_table('specifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='所属作用域节点 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="规范名称，如 'Study-001 SDTM Specification v1.0'"),
    sa.Column('spec_type', sa.Enum('SDTM', 'ADAM', name='spec_type_enum'), nullable=False, comment='规范类型：SDTM / ADaM'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='spec_status_enum'), nullable=False, comment='状态：Draft / Active / Archived'),
    sa.Column('description', sa.Text(), nullable=True, comment='规范描述'),
    sa.Column('standard_name', sa.String(length=100), nullable=True, comment="标准名称，如 'SDTM-IG 3.4'"),
    sa.Column('standard_version', sa.String(length=50), nullable=True, comment='标准版本'),
    sa.Column('base_specification_id', sa.Integer(), nullable=True, comment='基线 Spec ID（继承来源）'),
    sa.Column('metadata_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='元数据配置，如默认排序规则、命名约定等'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='激活时间'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_specification_id'], ['specifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='规范文档表 - SDTM/ADaM 完整规格定义'
    )
    op.create_index(op.f('ix_specifications_base_specification_id'), 'specifications', ['base_specification_id'], unique=False)
    op.create_index(op.f('ix_specifications_is_deleted'), 'specifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_specifications_scope_node_id'), 'specifications', ['scope_node_id'], unique=False)
    op.create_index(op.f('ix_specifications_spec_type'), 'specifications', ['spec_type'], unique=False)
    op.create_index(op.f('ix_specifications_status'), 'specifications', ['status'], unique=False)
    op.create_index('ix_specifications_type_status', 'specifications', ['spec_type', 'status'], unique=False)
    op.create_index('uix_specifications_scope_type_name', 'specifications', ['scope_node_id', 'spec_type', 'name'], unique=True)
    op.create_table('ars_display_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False, comment='所属 Display ID'),
    sa.Column('block_template_id', sa.Integer(), nullable=False, comment='关联的模板块 ID'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('override_layout_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='覆盖布局 Schema，用于局部修改模板'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_template_id'], ['ars_template_blocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['display_id'], ['ars_displays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='ARS 显示区块表 - Display 与 TemplateBlock 桥接'
    )
    op.create_index(op.f('ix_ars_display_sections_block_template_id'), 'ars_display_sections', ['block_template_id'], unique=False)
    op.create_index(op.f('ix_ars_display_sections_display_id'), 'ars_display_sections', ['display_id'], unique=False)
    op.create_index(op.f('ix_ars_display_sections_is_deleted'), 'ars_display_sections', ['is_deleted'], unique=False)
    op.create_index('uix_ars_sections_display_order', 'ars_display_sections', ['display_id', 'display_order'], unique=True)
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False, comment='所属源数据集合 ID'),
    sa.Column('item_name', sa.String(length=100), nullable=False, comment='字段名称（技术名称）'),
    sa.Column('item_oid', sa.String(length=100), nullable=True, comment='字段 OID（来自 EDC 系统的唯一标识）'),
    sa.Column('item_label', sa.String(length=200), nullable=True, comment='字段标签（显示名称）'),
    sa.Column('description', sa.Text(), nullable=True, comment='字段详细描述'),
    sa.Column('data_type', sa.String(length=50), nullable=True, comment='数据类型（来自源系统）'),
    sa.Column('field_text', sa.Text(), nullable=True, comment='字段在 CRF 上的显示文本，用于 PDF 文本匹配锚点'),
    sa.Column('pdf_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="PDF 坐标信息，格式: {'page': 1, 'x0': 100, 'y0': 200, 'x1': 300, 'y1': 220}"),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='集合内字段排序序号'),
    sa.Column('raw_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='原始属性，如 CodeList、验证规则、计算逻辑等'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['source_collections.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='源数据字段表 - EDC 字段定义（含 aCRF 锚点）'
    )
    op.create_index(op.f('ix_source_items_collection_id'), 'source_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_source_items_is_deleted'), 'source_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_source_items_item_name'), 'source_items', ['item_name'], unique=False)
    op.create_index('uix_source_items_collection_name', 'source_items', ['collection_id', 'item_name'], unique=True)
    op.create_table('target_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False, comment='所属规范文档 ID'),
    sa.Column('dataset_name', sa.String(length=8), nullable=False, comment='数据集名称，如 AE, DM, ADSL'),
    sa.Column('description', sa.Text(), nullable=True, comment='数据集描述'),
    sa.Column('class_type', sa.Enum('SPECIAL_PURPOSE', 'INTERVENTIONS', 'EVENTS', 'FINDINGS', 'FINDINGS_ABOUT', 'RELATIONSHIP', 'TRIAL_DESIGN', name='dataset_class_enum'), nullable=False, comment='SDTM 数据集分类：Interventions/Events/Findings 等'),
    sa.Column('base_id', sa.Integer(), nullable=True, comment='父级 Dataset ID（跨层级继承来源），NULL 表示顶层定义'),
    sa.Column('override_type', sa.Enum('NONE', 'MODIFIED', 'ADDED', 'DELETED', name='override_type_enum'), nullable=False, comment='继承覆盖类型：None(完全继承)/Modified(已修改)/Added(新增)/Deleted(已删除)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('standard_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标准元数据，如 CDISC 定义的结构、键变量等'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['target_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='目标数据集表 - SDTM/ADaM 数据集定义（归属于 Specification）'
    )
    op.create_index(op.f('ix_target_datasets_base_id'), 'target_datasets', ['base_id'], unique=False)
    op.create_index('ix_target_datasets_base_override', 'target_datasets', ['base_id', 'override_type'], unique=False)
    op.create_index(op.f('ix_target_datasets_dataset_name'), 'target_datasets', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_target_datasets_is_deleted'), 'target_datasets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_target_datasets_override_type'), 'target_datasets', ['override_type'], unique=False)
    op.create_index(op.f('ix_target_datasets_specification_id'), 'target_datasets', ['specification_id'], unique=False)
    op.create_index('uix_target_datasets_spec_name', 'target_datasets', ['specification_id', 'dataset_name'], unique=True)
    op.create_table('programming_trackers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False, comment='所属 Analysis 节点 ID'),
    sa.Column('deliverable_type', sa.Enum('SDTM', 'ADAM', 'TFL', name='deliverable_type_enum'), nullable=False, comment='交付物类型：SDTM / ADaM / TFL'),
    sa.Column('target_dataset_id', sa.Integer(), nullable=True, comment='关联的目标数据集 ID（SDTM/ADaM 任务）'),
    sa.Column('tfl_output_id', sa.Integer(), nullable=True, comment='关联的 TFL 输出 ID（TFL 任务）'),
    sa.Column('task_name', sa.String(length=200), nullable=False, comment="任务名称，如 'AE Dataset', 'Table 14.1.1'"),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('prod_programmer_id', sa.String(length=100), nullable=True, comment='生产程序员用户 ID'),
    sa.Column('qc_programmer_id', sa.String(length=100), nullable=True, comment='QC 程序员用户 ID'),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PROGRAMMING', 'READY_FOR_QC', 'QC_IN_PROGRESS', 'PASSED', 'FAILED', name='tracker_status_enum'), nullable=False, comment='任务状态：Not_Started/Programming/Ready_for_QC/QC_In_Progress/Passed/Failed'),
    sa.Column('qc_method', sa.Enum('DOUBLE_PROGRAMMING', 'SPOT_CHECK', 'REVIEW', name='qc_method_enum'), nullable=False, comment='QC 方法：Double_Programming/Spot_Check/Review'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('qc_started_at', sa.DateTime(timezone=True), nullable=True, comment='QC 开始时间'),
    sa.Column('qc_completed_at', sa.DateTime(timezone=True), nullable=True, comment='QC 完成时间'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='截止日期'),
    sa.Column('prod_file_path', sa.String(length=500), nullable=True, comment='生产程序文件路径'),
    sa.Column('qc_file_path', sa.String(length=500), nullable=True, comment='QC 程序文件路径'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_dataset_id'], ['target_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tfl_output_id'], ['ars_displays.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='编程任务追踪表 - 任务执行看板核心表'
    )
    op.create_index(op.f('ix_programming_trackers_analysis_id'), 'programming_trackers', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_programming_trackers_deliverable_type'), 'programming_trackers', ['deliverable_type'], unique=False)
    op.create_index(op.f('ix_programming_trackers_due_date'), 'programming_trackers', ['due_date'], unique=False)
    op.create_index(op.f('ix_programming_trackers_is_deleted'), 'programming_trackers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_programming_trackers_prod_programmer_id'), 'programming_trackers', ['prod_programmer_id'], unique=False)
    op.create_index(op.f('ix_programming_trackers_qc_programmer_id'), 'programming_trackers', ['qc_programmer_id'], unique=False)
    op.create_index(op.f('ix_programming_trackers_status'), 'programming_trackers', ['status'], unique=False)
    op.create_index(op.f('ix_programming_trackers_target_dataset_id'), 'programming_trackers', ['target_dataset_id'], unique=False)
    op.create_index(op.f('ix_programming_trackers_tfl_output_id'), 'programming_trackers', ['tfl_output_id'], unique=False)
    op.create_index('ix_trackers_analysis_status', 'programming_trackers', ['analysis_id', 'status'], unique=False)
    op.create_index('ix_trackers_programmer_status', 'programming_trackers', ['prod_programmer_id', 'status'], unique=False)
    op.create_table('target_variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属目标数据集 ID'),
    sa.Column('variable_name', sa.String(length=8), nullable=False, comment='变量名称，如 AETERM, VSORRES'),
    sa.Column('variable_label', sa.String(length=200), nullable=True, comment='变量标签'),
    sa.Column('description', sa.Text(), nullable=True, comment='变量详细描述'),
    sa.Column('data_type', sa.Enum('CHAR', 'NUM', 'DATE', 'DATETIME', 'TIME', name='data_type_enum'), nullable=False, comment='数据类型：Char/Num/Date/DateTime/Time'),
    sa.Column('length', sa.Integer(), nullable=True, comment='变量长度'),
    sa.Column('core', sa.Enum('REQ', 'PERM', 'EXP', name='variable_core_enum'), nullable=False, comment='核心性：Req(必须)/Perm(允许)/Exp(期望)'),
    sa.Column('base_id', sa.Integer(), nullable=True, comment='父级 Variable ID（跨层级继承来源），NULL 表示顶层定义'),
    sa.Column('override_type', sa.Enum('NONE', 'MODIFIED', 'ADDED', 'DELETED', name='override_type_enum'), nullable=False, comment='继承覆盖类型：None(完全继承)/Modified(已修改)/Added(新增)/Deleted(已删除)'),
    sa.Column('origin_type', sa.Enum('CDISC', 'SPONSOR_STANDARD', 'TA_STANDARD', 'STUDY_CUSTOM', name='origin_type_enum'), nullable=False, comment='变量来源：CDISC官方/企业标准/TA标准/试验自定义'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='数据集内变量排序序号'),
    sa.Column('standard_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标准元数据，如 CDISC 定义的 CodeList、角色等'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['target_variables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['target_datasets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='目标变量表 - SDTM/ADaM 变量定义（含来源与继承）'
    )
    op.create_index(op.f('ix_target_variables_base_id'), 'target_variables', ['base_id'], unique=False)
    op.create_index('ix_target_variables_base_override', 'target_variables', ['base_id', 'override_type'], unique=False)
    op.create_index(op.f('ix_target_variables_dataset_id'), 'target_variables', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_target_variables_is_deleted'), 'target_variables', ['is_deleted'], unique=False)
    op.create_index('ix_target_variables_origin', 'target_variables', ['origin_type'], unique=False)
    op.create_index(op.f('ix_target_variables_origin_type'), 'target_variables', ['origin_type'], unique=False)
    op.create_index(op.f('ix_target_variables_override_type'), 'target_variables', ['override_type'], unique=False)
    op.create_index(op.f('ix_target_variables_variable_name'), 'target_variables', ['variable_name'], unique=False)
    op.create_index('uix_target_variables_dataset_name', 'target_variables', ['dataset_id', 'variable_name'], unique=True)
    op.create_table('ars_data_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False, comment='所属 Section ID'),
    sa.Column('target_variable_id', sa.Integer(), nullable=False, comment='关联的目标变量 ID（ADaM）'),
    sa.Column('variable_role', sa.String(length=50), nullable=False, comment='变量角色：analysis / treatment / stratification / by'),
    sa.Column('filter_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='过滤逻辑，如 {\'where\': \'SAFFL = "Y"\'}'),
    sa.Column('statistics_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="统计量配置，如 {'n': true, 'mean': true, 'sd': true}"),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['ars_display_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_variable_id'], ['target_variables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='ARS 数据绑定表 - Section 与 TargetVariable 关联'
    )
    op.create_index(op.f('ix_ars_data_bindings_is_deleted'), 'ars_data_bindings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ars_data_bindings_section_id'), 'ars_data_bindings', ['section_id'], unique=False)
    op.create_index(op.f('ix_ars_data_bindings_target_variable_id'), 'ars_data_bindings', ['target_variable_id'], unique=False)
    op.create_index('uix_ars_bindings_section_var', 'ars_data_bindings', ['section_id', 'target_variable_id'], unique=True)
    op.create_table('mapping_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True, comment='源数据字段 ID（纯派生变量可为 NULL）'),
    sa.Column('target_variable_id', sa.Integer(), nullable=False, comment='目标变量 ID'),
    sa.Column('mapping_type', sa.String(length=20), nullable=False, comment='映射类型：direct（直接映射）/ derived（派生）/ compound（复合）'),
    sa.Column('derivation_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="多模态推导逻辑，如 {'sas': '...', 'r': '...', 'nl': '...'}"),
    sa.Column('direct_value', sa.Text(), nullable=True, comment="直接映射值（当 mapping_type='direct' 时使用）"),
    sa.Column('mapping_comment', sa.Text(), nullable=True, comment='映射说明注释'),
    sa.Column('visibility_context', sa.Enum('ALL', 'BLINDED_ONLY', 'UNBLINDED_ONLY', name='visibility_context_enum'), nullable=False, comment='可见性上下文：All/Blinded_Only/Unblinded_Only'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PRODUCTION', 'QCING', 'VALIDATED', name='mapping_status_enum'), nullable=False, comment='映射状态：Draft/In_Production/QCing/Validated'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号，每次验证通过后递增'),
    sa.Column('programmer_id', sa.String(length=100), nullable=True, comment='程序员用户 ID'),
    sa.Column('qcer_id', sa.String(length=100), nullable=True, comment='QC 审核员用户 ID'),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True, comment='验证通过时间'),
    sa.Column('validated_by', sa.String(length=100), nullable=True, comment='验证通过者用户 ID'),
    sa.Column('crf_page_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='CRF 页码列表（由 aCRF 引擎解析生成）'),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_variable_id'], ['target_variables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='映射规则表 - Mapping Studio 核心表'
    )
    op.create_index(op.f('ix_mapping_rules_is_deleted'), 'mapping_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_mapping_rules_programmer_id'), 'mapping_rules', ['programmer_id'], unique=False)
    op.create_index('ix_mapping_rules_programmer_status', 'mapping_rules', ['programmer_id', 'status'], unique=False)
    op.create_index(op.f('ix_mapping_rules_qcer_id'), 'mapping_rules', ['qcer_id'], unique=False)
    op.create_index('ix_mapping_rules_qcer_status', 'mapping_rules', ['qcer_id', 'status'], unique=False)
    op.create_index(op.f('ix_mapping_rules_source_item_id'), 'mapping_rules', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_mapping_rules_status'), 'mapping_rules', ['status'], unique=False)
    op.create_index('ix_mapping_rules_status_visibility', 'mapping_rules', ['status', 'visibility_context'], unique=False)
    op.create_index(op.f('ix_mapping_rules_target_variable_id'), 'mapping_rules', ['target_variable_id'], unique=False)
    op.create_index(op.f('ix_mapping_rules_visibility_context'), 'mapping_rules', ['visibility_context'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_rules_visibility_context'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_target_variable_id'), table_name='mapping_rules')
    op.drop_index('ix_mapping_rules_status_visibility', table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_status'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_source_item_id'), table_name='mapping_rules')
    op.drop_index('ix_mapping_rules_qcer_status', table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_qcer_id'), table_name='mapping_rules')
    op.drop_index('ix_mapping_rules_programmer_status', table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_programmer_id'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_is_deleted'), table_name='mapping_rules')
    op.drop_table('mapping_rules')
    op.drop_index('uix_ars_bindings_section_var', table_name='ars_data_bindings')
    op.drop_index(op.f('ix_ars_data_bindings_target_variable_id'), table_name='ars_data_bindings')
    op.drop_index(op.f('ix_ars_data_bindings_section_id'), table_name='ars_data_bindings')
    op.drop_index(op.f('ix_ars_data_bindings_is_deleted'), table_name='ars_data_bindings')
    op.drop_table('ars_data_bindings')
    op.drop_index('uix_target_variables_dataset_name', table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_variable_name'), table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_override_type'), table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_origin_type'), table_name='target_variables')
    op.drop_index('ix_target_variables_origin', table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_is_deleted'), table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_dataset_id'), table_name='target_variables')
    op.drop_index('ix_target_variables_base_override', table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_base_id'), table_name='target_variables')
    op.drop_table('target_variables')
    op.drop_index('ix_trackers_programmer_status', table_name='programming_trackers')
    op.drop_index('ix_trackers_analysis_status', table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_tfl_output_id'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_target_dataset_id'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_status'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_qc_programmer_id'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_prod_programmer_id'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_is_deleted'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_due_date'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_deliverable_type'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_analysis_id'), table_name='programming_trackers')
    op.drop_table('programming_trackers')
    op.drop_index('uix_target_datasets_spec_name', table_name='target_datasets')
    op.drop_index(op.f('ix_target_datasets_specification_id'), table_name='target_datasets')
    op.drop_index(op.f('ix_target_datasets_override_type'), table_name='target_datasets')
    op.drop_index(op.f('ix_target_datasets_is_deleted'), table_name='target_datasets')
    op.drop_index(op.f('ix_target_datasets_dataset_name'), table_name='target_datasets')
    op.drop_index('ix_target_datasets_base_override', table_name='target_datasets')
    op.drop_index(op.f('ix_target_datasets_base_id'), table_name='target_datasets')
    op.drop_table('target_datasets')
    op.drop_index('uix_source_items_collection_name', table_name='source_items')
    op.drop_index(op.f('ix_source_items_item_name'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_is_deleted'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_collection_id'), table_name='source_items')
    op.drop_table('source_items')
    op.drop_index('uix_ars_sections_display_order', table_name='ars_display_sections')
    op.drop_index(op.f('ix_ars_display_sections_is_deleted'), table_name='ars_display_sections')
    op.drop_index(op.f('ix_ars_display_sections_display_id'), table_name='ars_display_sections')
    op.drop_index(op.f('ix_ars_display_sections_block_template_id'), table_name='ars_display_sections')
    op.drop_table('ars_display_sections')
    op.drop_index('uix_specifications_scope_type_name', table_name='specifications')
    op.drop_index('ix_specifications_type_status', table_name='specifications')
    op.drop_index(op.f('ix_specifications_status'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_spec_type'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_scope_node_id'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_is_deleted'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_base_specification_id'), table_name='specifications')
    op.drop_table('specifications')
    op.drop_index('uix_source_collections_scope_name', table_name='source_collections')
    op.drop_index(op.f('ix_source_collections_scope_node_id'), table_name='source_collections')
    op.drop_index('ix_source_collections_oid', table_name='source_collections')
    op.drop_index(op.f('ix_source_collections_is_deleted'), table_name='source_collections')
    op.drop_index(op.f('ix_source_collections_collection_name'), table_name='source_collections')
    op.drop_table('source_collections')
    op.drop_index('ix_prs_source_type_status', table_name='metadata_pull_requests')
    op.drop_index('ix_prs_reviewer_status', table_name='metadata_pull_requests')
    op.drop_index('ix_prs_requester_status', table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_target_scope_id'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_status'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_source_scope_id'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_reviewer_id'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_requester_id'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_pr_number'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_item_type'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_item_id'), table_name='metadata_pull_requests')
    op.drop_index(op.f('ix_metadata_pull_requests_is_deleted'), table_name='metadata_pull_requests')
    op.drop_table('metadata_pull_requests')
    op.drop_index('ix_audit_logs_user_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_table_record', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_scope_node_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_pull_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uix_ars_blocks_scope_name', table_name='ars_template_blocks')
    op.drop_index(op.f('ix_ars_template_blocks_scope_node_id'), table_name='ars_template_blocks')
    op.drop_index(op.f('ix_ars_template_blocks_is_deleted'), table_name='ars_template_blocks')
    op.drop_index(op.f('ix_ars_template_blocks_block_name'), table_name='ars_template_blocks')
    op.drop_table('ars_template_blocks')
    op.drop_index('uix_ars_displays_scope_id', table_name='ars_displays')
    op.drop_index(op.f('ix_ars_displays_scope_node_id'), table_name='ars_displays')
    op.drop_index(op.f('ix_ars_displays_is_deleted'), table_name='ars_displays')
    op.drop_index(op.f('ix_ars_displays_display_id'), table_name='ars_displays')
    op.drop_table('ars_displays')
    op.drop_index('uix_workspaces_node_code', table_name='analysis_workspaces')
    op.drop_index('ix_workspaces_type_visibility', table_name='analysis_workspaces')
    op.drop_index('ix_workspaces_active', table_name='analysis_workspaces')
    op.drop_index(op.f('ix_analysis_workspaces_workspace_type'), table_name='analysis_workspaces')
    op.drop_index(op.f('ix_analysis_workspaces_scope_node_id'), table_name='analysis_workspaces')
    op.drop_index(op.f('ix_analysis_workspaces_is_deleted'), table_name='analysis_workspaces')
    op.drop_table('analysis_workspaces')
    op.drop_index('ix_scope_nodes_type_status', table_name='scope_nodes')
    op.drop_index('ix_scope_nodes_parent_type', table_name='scope_nodes')
    op.drop_index(op.f('ix_scope_nodes_parent_id'), table_name='scope_nodes')
    op.drop_index(op.f('ix_scope_nodes_node_type'), table_name='scope_nodes')
    op.drop_index(op.f('ix_scope_nodes_lifecycle_status'), table_name='scope_nodes')
    op.drop_index(op.f('ix_scope_nodes_is_deleted'), table_name='scope_nodes')
    op.drop_index(op.f('ix_scope_nodes_code'), table_name='scope_nodes')
    op.drop_index('ix_scope_nodes_active', table_name='scope_nodes')
    op.drop_table('scope_nodes')
    # ### end Alembic commands ###