"""upgrade tracker and add issue system

Revision ID: 8abcd7fde247
Revises: 9f67d4c6ab11
Create Date: 2026-03-05 16:06:16.061639+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8abcd7fde247'
down_revision: Union[str, None] = '9f67d4c6ab11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### 先创建新的枚举类型（使用 IF NOT EXISTS 避免重复创建） ###
    # 创建 prod_status_enum
    op.execute("DO $$ BEGIN CREATE TYPE prod_status_enum AS ENUM ('NOT_STARTED', 'PROGRAMMING', 'READY_FOR_QC', 'COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")
    # 创建 qc_status_enum
    op.execute("DO $$ BEGIN CREATE TYPE qc_status_enum AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'ISSUES_FOUND', 'PASSED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")
    # 创建 priority_enum
    op.execute("DO $$ BEGIN CREATE TYPE priority_enum AS ENUM ('HIGH', 'MEDIUM', 'LOW'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")
    # 创建 issue_status_enum
    op.execute("DO $$ BEGIN CREATE TYPE issue_status_enum AS ENUM ('OPEN', 'ANSWERED', 'RESOLVED', 'CLOSED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")

    # 更新 deliverable_type_enum 添加新值
    op.execute("DO $$ BEGIN ALTER TYPE deliverable_type_enum ADD VALUE 'OTHER_LOOKUP'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False, comment='关联的 Tracker ID'),
    sa.Column('qc_cycle', sa.String(length=50), nullable=False, comment="QC 轮次，如 'Dry Run 1', 'Dry Run 2', 'Final'"),
    sa.Column('finding_description', sa.Text(), nullable=False, comment='发现的问题描述'),
    sa.Column('finding_category', sa.String(length=100), nullable=True, comment="问题分类，如 'Logic Error', 'Data Issue', 'Formatting'"),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='严重程度：Critical / Major / Minor'),
    sa.Column('raised_by', sa.String(length=100), nullable=False, comment='提出人用户 ID'),
    sa.Column('raised_by_name', sa.String(length=200), nullable=True, comment='提出人姓名'),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False, comment='发现日期'),
    sa.Column('developer_response', sa.Text(), nullable=True, comment='程序员回复内容'),
    sa.Column('responded_by', sa.String(length=100), nullable=True, comment='回复人用户 ID'),
    sa.Column('responded_by_name', sa.String(length=200), nullable=True, comment='回复人姓名'),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True, comment='回复时间'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='解决说明'),
    sa.Column('resolved_by', sa.String(length=100), nullable=True, comment='解决确认人用户 ID'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='解决确认时间'),
    sa.Column('issue_status', postgresql.ENUM('OPEN', 'ANSWERED', 'RESOLVED', 'CLOSED', name='issue_status_enum', create_type=False), nullable=False, comment='Issue 状态：Open/Answered/Resolved/Closed'),
    sa.Column('attachment_paths', sa.Text(), nullable=True, comment='附件路径列表（JSON 数组字符串）'),
    sa.Column('extra_attrs', sa.Text(), nullable=True, comment='扩展属性（JSON 字符串）'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者用户 ID'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tracker_id'], ['programming_trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='QC Issue 记录表 - 多轮 QC 沟通系统'
    )
    op.create_index('ix_issues_raised_by', 'tracker_issues', ['raised_by', 'raised_at'], unique=False)
    op.create_index('ix_issues_tracker_cycle', 'tracker_issues', ['tracker_id', 'qc_cycle'], unique=False)
    op.create_index('ix_issues_tracker_status', 'tracker_issues', ['tracker_id', 'issue_status'], unique=False)
    op.create_index(op.f('ix_tracker_issues_is_deleted'), 'tracker_issues', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tracker_issues_issue_status'), 'tracker_issues', ['issue_status'], unique=False)
    op.create_index(op.f('ix_tracker_issues_qc_cycle'), 'tracker_issues', ['qc_cycle'], unique=False)
    op.create_index(op.f('ix_tracker_issues_tracker_id'), 'tracker_issues', ['tracker_id'], unique=False)
    # 添加 deliverable_name 列（先允许为空，填充数据后设为非空）
    op.add_column('programming_trackers', sa.Column('deliverable_name', sa.String(length=100), nullable=True, comment="交付物名称，如 'AE', 'Table 14.1.1'，方便快速查询"))
    # 用 task_name 填充 deliverable_name
    op.execute("UPDATE programming_trackers SET deliverable_name = task_name WHERE deliverable_name IS NULL")
    # 设为非空
    op.alter_column('programming_trackers', 'deliverable_name', nullable=False)

    # 添加 prod_status 列（先允许为空，填充数据后设为非空）
    op.add_column('programming_trackers', sa.Column('prod_status', sa.Enum('NOT_STARTED', 'PROGRAMMING', 'READY_FOR_QC', 'COMPLETED', name='prod_status_enum', create_type=False), nullable=True, comment='生产状态：Not_Started/Programming/Ready_for_QC/Completed'))
    # 用 status 填充 prod_status
    op.execute("""
        UPDATE programming_trackers
        SET prod_status = CASE
            WHEN status IN ('NOT_STARTED') THEN 'NOT_STARTED'::prod_status_enum
            WHEN status IN ('PROGRAMMING') THEN 'PROGRAMMING'::prod_status_enum
            WHEN status IN ('READY_FOR_QC', 'QC_IN_PROGRESS') THEN 'READY_FOR_QC'::prod_status_enum
            WHEN status IN ('PASSED', 'FAILED') THEN 'COMPLETED'::prod_status_enum
            ELSE 'NOT_STARTED'::prod_status_enum
        END
        WHERE prod_status IS NULL
    """)
    op.alter_column('programming_trackers', 'prod_status', nullable=False)

    # 添加 qc_status 列（先允许为空，填充数据后设为非空）
    op.add_column('programming_trackers', sa.Column('qc_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'ISSUES_FOUND', 'PASSED', name='qc_status_enum', create_type=False), nullable=True, comment='QC 状态：Not_Started/In_Progress/Issues_Found/Passed'))
    # 用 status 填充 qc_status
    op.execute("""
        UPDATE programming_trackers
        SET qc_status = CASE
            WHEN status IN ('QC_IN_PROGRESS') THEN 'IN_PROGRESS'::qc_status_enum
            WHEN status IN ('FAILED') THEN 'ISSUES_FOUND'::qc_status_enum
            WHEN status IN ('PASSED') THEN 'PASSED'::qc_status_enum
            ELSE 'NOT_STARTED'::qc_status_enum
        END
        WHERE qc_status IS NULL
    """)
    op.alter_column('programming_trackers', 'qc_status', nullable=False)

    # 添加 priority 列（先允许为空，填充默认值后设为非空）
    op.add_column('programming_trackers', sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority_enum', create_type=False), nullable=True, comment='优先级：High / Medium / Low'))
    op.execute("UPDATE programming_trackers SET priority = 'MEDIUM'::priority_enum WHERE priority IS NULL")
    op.alter_column('programming_trackers', 'priority', nullable=False)

    # 添加 execution_order 列（先允许为空，填充默认值后设为非空）
    op.add_column('programming_trackers', sa.Column('execution_order', sa.Integer(), nullable=True, comment='执行顺序（Derived order），决定执行先后'))
    op.execute("UPDATE programming_trackers SET execution_order = 0 WHERE execution_order IS NULL")
    op.alter_column('programming_trackers', 'execution_order', nullable=False)

    op.add_column('programming_trackers', sa.Column('tfl_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='TFL 专属元数据，如 output_number, title, footnote, population_source 等'))
    op.alter_column('programming_trackers', 'deliverable_type',
               existing_type=postgresql.ENUM('SDTM', 'ADAM', 'TFL', name='deliverable_type_enum'),
               comment='交付物类型：SDTM / ADaM / TFL / Other_Lookup',
               existing_comment='交付物类型：SDTM / ADaM / TFL',
               existing_nullable=False)
    op.alter_column('programming_trackers', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'PROGRAMMING', 'READY_FOR_QC', 'QC_IN_PROGRESS', 'PASSED', 'FAILED', name='tracker_status_enum'),
               comment='任务状态（旧版，保留兼容）',
               existing_comment='任务状态：Not_Started/Programming/Ready_for_QC/QC_In_Progress/Passed/Failed',
               existing_nullable=False)
    op.create_index(op.f('ix_programming_trackers_deliverable_name'), 'programming_trackers', ['deliverable_name'], unique=False)
    op.create_index(op.f('ix_programming_trackers_priority'), 'programming_trackers', ['priority'], unique=False)
    op.create_index(op.f('ix_programming_trackers_prod_status'), 'programming_trackers', ['prod_status'], unique=False)
    op.create_index(op.f('ix_programming_trackers_qc_status'), 'programming_trackers', ['qc_status'], unique=False)
    op.create_index('ix_trackers_analysis_prod_qc_status', 'programming_trackers', ['analysis_id', 'prod_status', 'qc_status'], unique=False)
    op.create_index('ix_trackers_priority_order', 'programming_trackers', ['analysis_id', 'priority', 'execution_order'], unique=False)
    op.create_table_comment(
        'programming_trackers',
        '编程任务追踪表 - 双轨状态机任务看板',
        existing_comment='编程任务追踪表 - 任务执行看板核心表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'programming_trackers',
        '编程任务追踪表 - 任务执行看板核心表',
        existing_comment='编程任务追踪表 - 双轨状态机任务看板',
        schema=None
    )
    op.drop_index('ix_trackers_priority_order', table_name='programming_trackers')
    op.drop_index('ix_trackers_analysis_prod_qc_status', table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_qc_status'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_prod_status'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_priority'), table_name='programming_trackers')
    op.drop_index(op.f('ix_programming_trackers_deliverable_name'), table_name='programming_trackers')
    op.alter_column('programming_trackers', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'PROGRAMMING', 'READY_FOR_QC', 'QC_IN_PROGRESS', 'PASSED', 'FAILED', name='tracker_status_enum'),
               comment='任务状态：Not_Started/Programming/Ready_for_QC/QC_In_Progress/Passed/Failed',
               existing_comment='任务状态（旧版，保留兼容）',
               existing_nullable=False)
    op.alter_column('programming_trackers', 'deliverable_type',
               existing_type=postgresql.ENUM('SDTM', 'ADAM', 'TFL', name='deliverable_type_enum'),
               comment='交付物类型：SDTM / ADaM / TFL',
               existing_comment='交付物类型：SDTM / ADaM / TFL / Other_Lookup',
               existing_nullable=False)
    op.drop_column('programming_trackers', 'tfl_metadata')
    op.drop_column('programming_trackers', 'execution_order')
    op.drop_column('programming_trackers', 'priority')
    op.drop_column('programming_trackers', 'qc_status')
    op.drop_column('programming_trackers', 'prod_status')
    op.drop_column('programming_trackers', 'deliverable_name')
    op.drop_index(op.f('ix_tracker_issues_tracker_id'), table_name='tracker_issues')
    op.drop_index(op.f('ix_tracker_issues_qc_cycle'), table_name='tracker_issues')
    op.drop_index(op.f('ix_tracker_issues_issue_status'), table_name='tracker_issues')
    op.drop_index(op.f('ix_tracker_issues_is_deleted'), table_name='tracker_issues')
    op.drop_index('ix_issues_tracker_status', table_name='tracker_issues')
    op.drop_index('ix_issues_tracker_cycle', table_name='tracker_issues')
    op.drop_index('ix_issues_raised_by', table_name='tracker_issues')
    op.drop_table('tracker_issues')

    # ### 删除枚举类型 ###
    op.execute("DROP TYPE IF EXISTS issue_status_enum")
    op.execute("DROP TYPE IF EXISTS priority_enum")
    op.execute("DROP TYPE IF EXISTS qc_status_enum")
    op.execute("DROP TYPE IF EXISTS prod_status_enum")
    # ### end Alembic commands ###