"""add physical scripts and delivery batch to tracker

Revision ID: 0ac04a15816c
Revises: 8abcd7fde247
Create Date: 2026-03-05 16:31:09.746816+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac04a15816c'
down_revision: Union[str, None] = '8abcd7fde247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_trackers', sa.Column('prod_program_name', sa.String(length=255), nullable=True, comment="Prod 程序文件名，如 'adsl.sas', 't_14_1_1.sas'"))
    op.add_column('programming_trackers', sa.Column('qc_program_name', sa.String(length=255), nullable=True, comment="QC 程序文件名，如 'v_adsl.sas', 'qc_t_14_1_1.sas'"))
    op.add_column('programming_trackers', sa.Column('output_file_name', sa.String(length=255), nullable=True, comment="最终生成的物理文件名，如 'adsl.sas7bdat', 't_14_1_1.rtf'"))
    op.add_column('programming_trackers', sa.Column('delivery_batch', sa.String(length=100), nullable=True, comment="交付批次标记，如 'Batch 1', 'Interim', 'Final'"))
    op.create_index(op.f('ix_programming_trackers_delivery_batch'), 'programming_trackers', ['delivery_batch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programming_trackers_delivery_batch'), table_name='programming_trackers')
    op.drop_column('programming_trackers', 'delivery_batch')
    op.drop_column('programming_trackers', 'output_file_name')
    op.drop_column('programming_trackers', 'qc_program_name')
    op.drop_column('programming_trackers', 'prod_program_name')
    # ### end Alembic commands ###