"""change_term_name_to_text

Revision ID: 234ed8f6a5d8
Revises: e94e157ebf59
Create Date: 2026-03-09 08:25:05.982459+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234ed8f6a5d8'
down_revision: Union[str, None] = 'e94e157ebf59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codelist_terms', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='术语名称',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codelist_terms', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='术语名称',
               existing_nullable=True)
    # ### end Alembic commands ###