"""tfl_study_templates_001

Revision ID: 393f43c88771
Revises: rbac_seed_001
Create Date: 2026-03-29 01:07:36.437725+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.base import JSONB


# revision identifiers, used by Alembic.
revision: str = '393f43c88771'
down_revision: Union[str, None] = 'rbac_seed_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='所属 study scope node'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='集合名称'),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='统计量集合表'
    )
    op.create_index(op.f('ix_statistics_sets_is_deleted'), 'statistics_sets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_statistics_sets_scope_node_id'), 'statistics_sets', ['scope_node_id'], unique=False)
    op.create_index('uix_stat_sets_scope_name', 'statistics_sets', ['scope_node_id', 'name'], unique=True)
    op.create_table('ars_study_defaults',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='Study scope node (1:1)'),
    sa.Column('default_statistics_set_id', sa.Integer(), nullable=True, comment='默认统计量集合'),
    sa.Column('decimal_rules', JSONB(), nullable=False, comment='{"n":0, "mean":2, "sd":3, "percent":2, "median":1, "min":1, "max":1}'),
    sa.Column('header_style', JSONB(), nullable=True, comment='默认 header 样式'),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['default_statistics_set_id'], ['statistics_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Study 级全局默认配置'
    )
    op.create_index(op.f('ix_ars_study_defaults_is_deleted'), 'ars_study_defaults', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ars_study_defaults_scope_node_id'), 'ars_study_defaults', ['scope_node_id'], unique=True)
    op.create_table('ars_study_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_node_id', sa.Integer(), nullable=False, comment='Study scope node'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Demographics / Adverse_Events / ...'),
    sa.Column('template_name', sa.String(length=200), nullable=False, comment='模板名称'),
    sa.Column('display_type', sa.String(length=20), nullable=False, comment='Table / Figure / Listing'),
    sa.Column('shell_schema', JSONB(), nullable=False, comment='完整 shell 定义 (TableShell/FigureShell/ListingShell 结构)'),
    sa.Column('statistics_set_id', sa.Integer(), nullable=True, comment='关联的统计量集合'),
    sa.Column('decimal_override', JSONB(), nullable=True, comment='模板级小数位覆盖 (与 Study Defaults 合并)'),
    sa.Column('version', sa.Integer(), nullable=False, comment='模板版本号'),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scope_node_id'], ['scope_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['statistics_set_id'], ['statistics_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Study 级 Shell 模板库'
    )
    op.create_index(op.f('ix_ars_study_templates_is_deleted'), 'ars_study_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ars_study_templates_scope_node_id'), 'ars_study_templates', ['scope_node_id'], unique=False)
    op.create_index('uix_ars_study_templates_scope_cat_name', 'ars_study_templates', ['scope_node_id', 'category', 'template_name'], unique=True)
    op.create_table('statistics_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statistics_set_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=30), nullable=False, comment='n / mean / sd / median / min / max / range / n_percent / header'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='显示标签'),
    sa.Column('format', sa.String(length=50), nullable=True, comment='格式模板 e.g. XX.X (X.XX)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statistics_set_id'], ['statistics_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='统计量条目表'
    )
    op.create_index(op.f('ix_statistics_items_statistics_set_id'), 'statistics_items', ['statistics_set_id'], unique=False)
    op.create_index('uix_stat_items_set_order', 'statistics_items', ['statistics_set_id', 'sort_order'], unique=True)
    op.add_column('ars_displays', sa.Column('source_template_id', sa.Integer(), nullable=True, comment='来源 Shell 模板 ID'))
    op.add_column('ars_displays', sa.Column('source_template_version', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='来源模板版本快照'))
    op.add_column('ars_displays', sa.Column('decimal_override', JSONB(), nullable=True, comment='Shell 级小数位覆盖'))
    op.add_column('ars_displays', sa.Column('statistics_set_id', sa.Integer(), nullable=True, comment='关联的统计量集合 ID'))
    op.create_index(op.f('ix_ars_displays_source_template_id'), 'ars_displays', ['source_template_id'], unique=False)
    op.create_index(op.f('ix_ars_displays_statistics_set_id'), 'ars_displays', ['statistics_set_id'], unique=False)
    op.create_foreign_key(None, 'ars_displays', 'statistics_sets', ['statistics_set_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ars_displays', 'ars_study_templates', ['source_template_id'], ['id'], ondelete='SET NULL')
    # Add ShellTemplateUpdate to pr_item_type_enum
    op.execute("ALTER TYPE pr_item_type_enum ADD VALUE IF NOT EXISTS 'ShellTemplateUpdate'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: pr_item_type_enum ShellTemplateUpdate cannot be removed (PostgreSQL limitation)
    op.drop_constraint(None, 'ars_displays', type_='foreignkey')
    op.drop_constraint(None, 'ars_displays', type_='foreignkey')
    op.drop_index(op.f('ix_ars_displays_statistics_set_id'), table_name='ars_displays')
    op.drop_index(op.f('ix_ars_displays_source_template_id'), table_name='ars_displays')
    op.drop_column('ars_displays', 'statistics_set_id')
    op.drop_column('ars_displays', 'decimal_override')
    op.drop_column('ars_displays', 'source_template_version')
    op.drop_column('ars_displays', 'source_template_id')
    op.drop_index('uix_stat_items_set_order', table_name='statistics_items')
    op.drop_index(op.f('ix_statistics_items_statistics_set_id'), table_name='statistics_items')
    op.drop_table('statistics_items')
    op.drop_index('uix_ars_study_templates_scope_cat_name', table_name='ars_study_templates')
    op.drop_index(op.f('ix_ars_study_templates_scope_node_id'), table_name='ars_study_templates')
    op.drop_index(op.f('ix_ars_study_templates_is_deleted'), table_name='ars_study_templates')
    op.drop_table('ars_study_templates')
    op.drop_index(op.f('ix_ars_study_defaults_scope_node_id'), table_name='ars_study_defaults')
    op.drop_index(op.f('ix_ars_study_defaults_is_deleted'), table_name='ars_study_defaults')
    op.drop_table('ars_study_defaults')
    op.drop_index('uix_stat_sets_scope_name', table_name='statistics_sets')
    op.drop_index(op.f('ix_statistics_sets_scope_node_id'), table_name='statistics_sets')
    op.drop_index(op.f('ix_statistics_sets_is_deleted'), table_name='statistics_sets')
    op.drop_table('statistics_sets')
    # ### end Alembic commands ###