"""change_term_value_to_text

Revision ID: e94e157ebf59
Revises: sdtm_class_enum_001
Create Date: 2026-03-09 07:32:20.902826+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e94e157ebf59'
down_revision: Union[str, None] = 'sdtm_class_enum_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codelist_terms', 'term_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='术语值，如 M, F, U',
               existing_nullable=False)
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限编码（如 mapping:edit）',
               existing_comment='权限编码',
               existing_nullable=False)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='权限名称（显示用）',
               existing_comment='权限名称',
               existing_nullable=False)
    op.alter_column('permissions', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='权限分类（project/metadata/qc/admin）',
               existing_comment='权限分类',
               existing_nullable=False)
    op.alter_column('permissions', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('permissions_code_key', 'permissions', type_='unique')
    op.alter_column('roles', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='角色编码（如 SUPER_ADMIN, PROGRAMMER）',
               existing_comment='角色编码',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='角色名称（显示用）',
               existing_comment='角色名称',
               existing_nullable=False)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否系统内置角色（不可删除）',
               existing_comment='是否系统内置',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('roles', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='创建者',
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_constraint('roles_code_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.alter_column('user_scope_roles', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='授权时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_scope_roles', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生效时间',
               existing_nullable=True)
    op.alter_column('user_scope_roles', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='失效时间',
               existing_nullable=True)
    op.alter_column('user_scope_roles', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='扩展属性',
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='是否超级管理员（跳过所有权限检查）',
               existing_comment='是否超级管理员',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_external_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_external_id_key', 'users', ['external_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='是否超级管理员',
               existing_comment='是否超级管理员（跳过所有权限检查）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_scope_roles', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展属性',
               existing_nullable=True)
    op.alter_column('user_scope_roles', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='失效时间',
               existing_nullable=True)
    op.alter_column('user_scope_roles', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生效时间',
               existing_nullable=True)
    op.alter_column('user_scope_roles', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='授权时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.create_unique_constraint('roles_code_key', 'roles', ['code'])
    op.alter_column('roles', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='创建者',
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('roles', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否系统内置',
               existing_comment='是否系统内置角色（不可删除）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='角色名称',
               existing_comment='角色名称（显示用）',
               existing_nullable=False)
    op.alter_column('roles', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='角色编码',
               existing_comment='角色编码（如 SUPER_ADMIN, PROGRAMMER）',
               existing_nullable=False)
    op.create_unique_constraint('permissions_code_key', 'permissions', ['code'])
    op.alter_column('permissions', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('permissions', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='权限分类',
               existing_comment='权限分类（project/metadata/qc/admin）',
               existing_nullable=False)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='权限名称',
               existing_comment='权限名称（显示用）',
               existing_nullable=False)
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限编码',
               existing_comment='权限编码（如 mapping:edit）',
               existing_nullable=False)
    op.alter_column('codelist_terms', 'term_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='术语值，如 M, F, U',
               existing_nullable=False)
    # ### end Alembic commands ###