"""expand cdisc string lengths

Revision ID: 543b3436cf86
Revises: bc_ct_models_001
Create Date: 2026-03-06 00:50:50.485020+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543b3436cf86'
down_revision: Union[str, None] = 'bc_ct_models_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biomedical_concepts', 'scope_node_id',
               existing_type=sa.INTEGER(),
               comment='所属 CDISC 标准节点 ID',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'concept_id',
               existing_type=sa.VARCHAR(length=100),
               comment='CDISC 概念 ID',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'ncit_code',
               existing_type=sa.VARCHAR(length=50),
               comment='NCI Thesaurus 编码，用于跨标准映射',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'short_name',
               existing_type=sa.VARCHAR(length=255),
               comment='概念短名称',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'definition',
               existing_type=sa.TEXT(),
               comment='概念定义',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='同义词列表，支持多语言',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'data_element_concepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='数据元素概念，定义数据类型、格式等',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'standard_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='CDISC 原始元数据',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='扩展属性',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('biomedical_concepts', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='创建者',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment='最后更新者',
               existing_nullable=True)
    op.create_index(op.f('ix_biomedical_concepts_is_deleted'), 'biomedical_concepts', ['is_deleted'], unique=False)
    op.create_index('ix_biomedical_concepts_ncit', 'biomedical_concepts', ['ncit_code'], unique=False)
    op.alter_column('codelist_terms', 'codelist_id',
               existing_type=sa.INTEGER(),
               comment='所属编码列表 ID',
               existing_nullable=False)
    op.alter_column('codelist_terms', 'term_id',
               existing_type=sa.VARCHAR(length=100),
               comment='术语 ID',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'term_value',
               existing_type=sa.VARCHAR(length=255),
               comment='术语值，如 M, F, U',
               existing_nullable=False)
    op.alter_column('codelist_terms', 'ncit_code',
               existing_type=sa.VARCHAR(length=50),
               comment='NCI Thesaurus 编码',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='术语名称',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'definition',
               existing_type=sa.TEXT(),
               comment='术语定义',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='同义词列表',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'submission_value',
               existing_type=sa.VARCHAR(length=255),
               comment='提交值',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'standard_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='CDISC 原始元数据',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='扩展属性',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('codelist_terms', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='创建者',
               existing_nullable=False)
    op.alter_column('codelist_terms', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment='最后更新者',
               existing_nullable=True)
    op.create_index(op.f('ix_codelist_terms_is_deleted'), 'codelist_terms', ['is_deleted'], unique=False)
    op.alter_column('codelists', 'scope_node_id',
               existing_type=sa.INTEGER(),
               comment='所属 CDISC 标准节点 ID',
               existing_nullable=False)
    op.alter_column('codelists', 'codelist_id',
               existing_type=sa.VARCHAR(length=100),
               comment='CDISC Codelist ID',
               existing_nullable=False)
    op.alter_column('codelists', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='编码列表名称',
               existing_nullable=False)
    op.alter_column('codelists', 'ncit_code',
               existing_type=sa.VARCHAR(length=50),
               comment='NCI Thesaurus 编码',
               existing_nullable=True)
    op.alter_column('codelists', 'definition',
               existing_type=sa.TEXT(),
               comment='编码列表定义',
               existing_nullable=True)
    op.alter_column('codelists', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='同义词列表',
               existing_nullable=True)
    op.alter_column('codelists', 'preferred_term',
               existing_type=sa.VARCHAR(length=255),
               comment='首选术语',
               existing_nullable=True)
    op.alter_column('codelists', 'submission_value',
               existing_type=sa.VARCHAR(length=255),
               comment='提交值',
               existing_nullable=True)
    op.alter_column('codelists', 'standard_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='CDISC 原始元数据',
               existing_nullable=True)
    op.alter_column('codelists', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='扩展属性',
               existing_nullable=True)
    op.alter_column('codelists', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('codelists', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='创建者',
               existing_nullable=False)
    op.alter_column('codelists', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment='最后更新者',
               existing_nullable=True)
    op.create_index(op.f('ix_codelists_is_deleted'), 'codelists', ['is_deleted'], unique=False)
    op.alter_column('target_datasets', 'dataset_name',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=255),
               comment='数据集名称，如 AE, DM, ADSL, General Observations',
               existing_comment='数据集名称，如 AE, DM, ADSL',
               existing_nullable=False)
    op.alter_column('target_variables', 'variable_name',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=255),
               comment='变量名称，如 AETERM, VSORRES, --DECOD',
               existing_comment='变量名称，如 AETERM, VSORRES',
               existing_nullable=False)
    op.alter_column('target_variables', 'variable_label',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_comment='变量标签',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_variables', 'variable_label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_comment='变量标签',
               existing_nullable=True)
    op.alter_column('target_variables', 'variable_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=8),
               comment='变量名称，如 AETERM, VSORRES',
               existing_comment='变量名称，如 AETERM, VSORRES, --DECOD',
               existing_nullable=False)
    op.alter_column('target_datasets', 'dataset_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=8),
               comment='数据集名称，如 AE, DM, ADSL',
               existing_comment='数据集名称，如 AE, DM, ADSL, General Observations',
               existing_nullable=False)
    op.drop_index(op.f('ix_codelists_is_deleted'), table_name='codelists')
    op.alter_column('codelists', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='最后更新者',
               existing_nullable=True)
    op.alter_column('codelists', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='创建者',
               existing_nullable=False)
    op.alter_column('codelists', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('codelists', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展属性',
               existing_nullable=True)
    op.alter_column('codelists', 'standard_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='CDISC 原始元数据',
               existing_nullable=True)
    op.alter_column('codelists', 'submission_value',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='提交值',
               existing_nullable=True)
    op.alter_column('codelists', 'preferred_term',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='首选术语',
               existing_nullable=True)
    op.alter_column('codelists', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='同义词列表',
               existing_nullable=True)
    op.alter_column('codelists', 'definition',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='编码列表定义',
               existing_nullable=True)
    op.alter_column('codelists', 'ncit_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NCI Thesaurus 编码',
               existing_nullable=True)
    op.alter_column('codelists', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='编码列表名称',
               existing_nullable=False)
    op.alter_column('codelists', 'codelist_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='CDISC Codelist ID',
               existing_nullable=False)
    op.alter_column('codelists', 'scope_node_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属 CDISC 标准节点 ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_codelist_terms_is_deleted'), table_name='codelist_terms')
    op.alter_column('codelist_terms', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='最后更新者',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='创建者',
               existing_nullable=False)
    op.alter_column('codelist_terms', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('codelist_terms', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展属性',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'standard_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='CDISC 原始元数据',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'submission_value',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='提交值',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='同义词列表',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'definition',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='术语定义',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='术语名称',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'ncit_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NCI Thesaurus 编码',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'term_value',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='术语值，如 M, F, U',
               existing_nullable=False)
    op.alter_column('codelist_terms', 'term_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='术语 ID',
               existing_nullable=True)
    op.alter_column('codelist_terms', 'codelist_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属编码列表 ID',
               existing_nullable=False)
    op.drop_index('ix_biomedical_concepts_ncit', table_name='biomedical_concepts')
    op.drop_index(op.f('ix_biomedical_concepts_is_deleted'), table_name='biomedical_concepts')
    op.alter_column('biomedical_concepts', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='最后更新者',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='创建者',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序序号',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('biomedical_concepts', 'extra_attrs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展属性',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'standard_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='CDISC 原始元数据',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'data_element_concepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='数据元素概念，定义数据类型、格式等',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='同义词列表，支持多语言',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'definition',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='概念定义',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'short_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='概念短名称',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'ncit_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NCI Thesaurus 编码，用于跨标准映射',
               existing_nullable=True)
    op.alter_column('biomedical_concepts', 'concept_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='CDISC 概念 ID',
               existing_nullable=False)
    op.alter_column('biomedical_concepts', 'scope_node_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属 CDISC 标准节点 ID',
               existing_nullable=False)
    # ### end Alembic commands ###